### ISSUE TITLE
Pipeline doesn't upload releases to S3

### ISSUE THREAD

**Issue by taurelius** [ovotech/cloud-key-rotator#242]
The CircleCI pipeline doesn't upload releases to the [public S3 bucket](https://s3.console.aws.amazon.com/s3/buckets/ckr-terraform-module-code/?region=eu-west-1&tab=overview). Currently I can only see one release in the bucket which I assume was uploaded manually.

This causes the Terraform module to fail when applying any plan that specifies any `ckr_version` other than `0.27.18`

https://github.com/ovotech/cloud-key-rotator/blob/master/tf_module/ckr/main.tf#L107

**Comment by taurelius** [comment]
Duplicate of #275

**Comment by eversC** [comment]
fixed in #313
