### ISSUE TITLE
Test improvement proposal

### ISSUE THREAD

**Issue by eversC** [ovotech/cloud-key-rotator#51]
- [x] mock call to ovotech/cloud-key-client
- [x] local key writer
- [x] Unit tests  public `Rotate()` func

- [ ] Add e2e tests for all key writers with real resources

**Comment by siwally** [comment]
Current thoughts are that it's not worth introducing Testify or a similar mocking framework, given we only have a handful of functions to swap in.

Might just mock the function in cases where we don't have an interface, in which case the function can be called anything as long as the signature is the same.  See https://stackoverflow.com/questions/19167970/mock-functions-in-go (option 1).

**Comment by siwally** [comment]
Attempting to use cloud-key-client instead of mocking it, but to plug in a new local (i.e. mock) provider type in addition to AWS and GCP.  Working in a separate branch (pluggable-providers) on cloud-key-client also.

**Comment by eversC** [comment]
Closing this one off as unit tests have been added.

e2e tests are a good idea, will raise another issue for that.

**Comment by eversC** [comment]
In fact, one already exists.... #34
